controller_list:
  - name: fake_arm_controller
    type: interpolate
    joints:
      - j2n6s300_joint_1
      - j2n6s300_joint_2
      - j2n6s300_joint_3
      - j2n6s300_joint_4
      - j2n6s300_joint_5
      - j2n6s300_joint_6

initial:
  - group: arm
    pose: Home
