arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin 
  #kinematics_solver: j2n6s300_arm_kinematics/IKFastKinematicsPlugin
  #kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_attempts: 3
  kinematics_solver_search_resolution: 0.001
  kinematics_solver_timeout: 0.05
  solve_type: Distance #Distance #Speed, Manipulation1
